name: Webhook on Event

on: [push, issues, pull_request]

jobs:
  webhook-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to webhook
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" \
          -X POST -d '{
            "username": "GitHub Notifier",
            "content": "@everyone",
            "sender": {
              "name": "${{ github.actor }}",
              "url": "https://github.com/${{ github.actor }}",
              "avatar": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
            },
            "embeds": [
              {
                "type": "rich",
                "title": "New Repository Activity",
                "description": "An event just occurred in the repository **${{ github.repository }}**",
                "color": 2123412,
                "fields": [
                  {
                    "name": "Triggered by",
                    "value": "${{ github.actor }}",
                    "inline": true
                  },
                  {
                    "name": "Event Type",
                    "value": "${{ github.event_name }}",
                    "inline": true
                  }
                ],
                "thumbnail": {
                  "url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
                },
                "author": {
                  "name": "${{ github.actor }}",
                  "url": "https://github.com/${{ github.actor }}",
                  "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
                },
                "url": "https://github.com/${{ github.repository }}"
              }
            ]
          }' ${{ secrets.WEBHOOK_URL }})
          echo "Webhook server response: $RESPONSE"
