name: Webhook on Event

on: [milestone, create, delete, fork, issues, member, pull_request, pull_request_review, issue_comment, push]

jobs:
  webhook-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to webhook
        run: |
          RESPONSE=$(curl -H "Content-Type: application/json" \
          -X POST -d '{
            "username": "GitHub Notifier",
            "content": "@admin",
            "sender": {
              "login": "${{ github.actor }}",
              "id": ${{ github.actor_id }},
              "node_id": "U_kgDODWqFXA",
              "avatar_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/${{ github.actor }}",
              "html_url": "https://github.com/${{ github.actor }}",
              "followers_url": "https://api.github.com/users/${{ github.actor }}/followers",
              "following_url": "https://api.github.com/users/${{ github.actor }}/following{/other_user}",
              "gists_url": "https://api.github.com/users/${{ github.actor }}/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/${{ github.actor }}/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/${{ github.actor }}/subscriptions",
              "organizations_url": "https://api.github.com/users/${{ github.actor }}/orgs",
              "repos_url": "https://api.github.com/users/${{ github.actor }}/repos",
              "events_url": "https://api.github.com/users/${{ github.actor }}/events{/privacy}",
              "received_events_url": "https://api.github.com/users/${{ github.actor }}/received_events",
              "type": "User",
              "user_view_type": "public",
              "site_admin": false
            },
            "embeds": [
              {
                "type": "rich",
                "title": "Something is happening on GitHubn",
                "description": "An event just occurred in the repository **${{ github.repository }}**",
                "color": 2123412,
                "fields": [
                  {
                    "name": "Triggered by",
                    "value": "${{ github.actor }}",
                    "inline": true
                  },
                  {
                    "name": "Event Type",
                    "value": "${{ github.event_name }}",
                    "inline": true
                  }
                ],
                "thumbnail": {
                  "url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
                },
                "author": {
                  "name": "${{ github.actor }}",
                  "url": "https://github.com/${{ github.actor }}",
                  "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
                },
                "url": "https://github.com/${{ github.repository }}"
              }
            ]
          }' ${{ secrets.WEBHOOK_URL }})
          echo "Webhook server response: $RESPONSE"
